### ISSUE TITLE
AttributeError: 'Motor' object has no attribute '_directory'

### ISSUE THREAD

**Issue by timmmerlan** [QuirkyCort/ev3dev-lang-python-fast#1]
Hi,
I was just trying to use ev3fast, but always get an error when trying to execute the program on the EV3:

robot@ev3dev:~/Python$ ./test.py
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    A_Motor = ev3.Motor('outA')
  File "/home/robot/Python/ev3fast.py", line 400, in __init__
    self._pre_open()
  File "/home/robot/Python/ev3fast.py", line 405, in _pre_open
    fd = os.open(self._directory + pre_open[0], pre_open[1])
AttributeError: 'Motor' object has no attribute '_directory'

My code starts with:
`#!/usr/bin/env python3
import ev3dev.ev3 as ev3
import ev3fast as ev3
import time
from datetime import datetime

A_Motor = ev3.Motor('outA')
`

I am using  brickman v0.10.0 with Kernel 4.14.80-ev3dev-2.3.1-ev3

Do you have an idea what I may do wrong?
Thank you in advance for your help!
Tim

**Comment by QuirkyCort** [comment]
Sorry for the late reply. Had always assumed that github will drop me an email if any new issues are opened and never checked this page (...I don't normally use github).

Anyway, the problem you faced is due to differences between how Stretch and Jessie name their ports. I fixed that in an earlier commit for sensors, but missed out the same for the motors.

I've just merged in a PR from 98moonlight that should fix this problem, as well as update the API to match ev3dev2. Didn't test it myself, so let me know if anything breaks.
